server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: lossreport
          uri: http://localhost:8082
          predicates:
            - Path=/lossReports/**, 
        - id: mylossinfo
          uri: http://localhost:8083
          predicates:
            - Path=/lossInfoManagements/**, /lossInformations/**
        - id: admin
          uri: http://localhost:8084
          predicates:
            - Path=/serviceManagements/**, 
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path=/alarmManagements/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: lossreport
          uri: http://lossreport:8080
          predicates:
            - Path=/lossReports/**, 
        - id: mylossinfo
          uri: http://mylossinfo:8080
          predicates:
            - Path=/lossInfoManagements/**, 
        - id: admin
          uri: http://admin:8080
          predicates:
            - Path=/serviceManagements/**, 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/alarmManagements/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
